Disabled ARM intrinsics because of compiler errors
Lots of type mismatch errors, e.g.
SDL_ttf.c:772:41: error: incompatible type for argument 2 of 'vorrq_u32'
  772 |             r2  = vorrq_u32(d2, sx23.val[0]);           // or
      |                                 ~~~~~~~~^~~
      |                                         |
      |                                         uint8x16_t